/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountryCard: typeof import('./../components/country/Card.vue')['default']
    LayoutHeader: typeof import('./../components/layout/Header.vue')['default']
    LoadingLoading: typeof import('./../components/loading/Loading.vue')['default']
    RouterLink: typeof import('vue-router/auto')['RouterLink']
    RouterView: typeof import('vue-router/auto')['RouterView']
    UIEmpty: typeof import('./../components/UI/Empty.vue')['default']
    UIInput: typeof import('./../components/UI/Input.vue')['default']
    UISelect: typeof import('./../components/UI/Select.vue')['default']
  }
}
